export const FETCH_MATCH = 'FETCH_MATCH'
export const GET_MATCH_PENDING = 'GET_MATCH_PENDING';
export const GET_MATCH_SUCCESS = 'GET_MATCH_SUCCESS';
export const GET_MATCH_FAILURE = 'GET_MATCH_FAILURE';
