export const FETCH_MATCH = 'FETCH_MATCH'
// export const GET_MATCH_PENDING = 'GET_MATCH_PENDING';
export const GET_MATCHES_SUCCESS = 'GET_MATCHES_SUCCESS';
export const GET_MATCH_FAILURE = 'GET_MATCH_FAILURE';
export const GET_RESULTS_SUCCESS = 'GET_RESULTS_SUCCESS';
